---
# inclusion des tâches communes
# Attention : - def_env devrait toujours être premier !
#             - ne mettre des tâches utilisant les
#               variables d'environnement (dev, ...) que
#               s'il s'agit de tâches systèmes devant
#               être définies partout !

  - include: def_env.yml
  
  # la gestion dela rotation des logs ne se fait que sur Linux
  - include: logrotate.yml
    when: ansible_system == "Linux"
    
  - include: motd.yml